package com.redhat.rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleWrapper implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean chamadaWebservice;
   private java.lang.String destinatarioEmail;

   public RuleWrapper()
   {
   }

   public java.lang.Boolean getChamadaWebservice()
   {
      return this.chamadaWebservice;
   }

   public void setChamadaWebservice(java.lang.Boolean chamadaWebservice)
   {
      this.chamadaWebservice = chamadaWebservice;
   }

   public java.lang.String getDestinatarioEmail()
   {
      return this.destinatarioEmail;
   }

   public void setDestinatarioEmail(java.lang.String destinatarioEmail)
   {
      this.destinatarioEmail = destinatarioEmail;
   }

   public RuleWrapper(java.lang.Boolean chamadaWebservice,
         java.lang.String destinatarioEmail)
   {
      this.chamadaWebservice = chamadaWebservice;
      this.destinatarioEmail = destinatarioEmail;
   }

}