package com.redhat.human_tasks;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Relatorio implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String campo1;
   private java.lang.String campo2;
   private java.lang.String campo3;
   private java.lang.String campo4;

   public Relatorio()
   {
   }

   public java.lang.String getCampo1()
   {
      return this.campo1;
   }

   public void setCampo1(java.lang.String campo1)
   {
      this.campo1 = campo1;
   }

   public java.lang.String getCampo2()
   {
      return this.campo2;
   }

   public void setCampo2(java.lang.String campo2)
   {
      this.campo2 = campo2;
   }

   public java.lang.String getCampo3()
   {
      return this.campo3;
   }

   public void setCampo3(java.lang.String campo3)
   {
      this.campo3 = campo3;
   }

   public java.lang.String getCampo4()
   {
      return this.campo4;
   }

   public void setCampo4(java.lang.String campo4)
   {
      this.campo4 = campo4;
   }

   public Relatorio(java.lang.String campo1, java.lang.String campo2,
         java.lang.String campo3, java.lang.String campo4)
   {
      this.campo1 = campo1;
      this.campo2 = campo2;
      this.campo3 = campo3;
      this.campo4 = campo4;
   }

}