package com.redhat.human_tasks;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Relatorio implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Relatorio() {
    }

}